name: Testes unitarios e e2e

on:
  push:
    branches:
      - main

jobs:
  teste-angular-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Testes
        run: npm run cypress:headles